aspclass5/Models/ErrorViewModel.cs
namespace aspclass5.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

aspclass5/Models/Hide.cs
namespace aspclass5.Models
{
    public class Hide
    {
        public string CardHolderName { get; set; }
        public int Cvv { get; set; } = 333;
    }
}

aspclass5/Models/Shopping.cs
namespace aspclass5.Models
{
    public class Shopping
    {
        public int RegNo { get; set; }
        public string ShopName { get; set; }
        public string Location { get; set; }
        public int CustomerRating { get; set; }

    }
}

aspclass5/Controllers/CookieController.cs
using Microsoft.AspNetCore.Mvc;

namespace aspclass5.Controllers
{
    public class CookieController : Controller
    {

        private string userName;

        [HttpGet]
        public IActionResult Index()
        {
            userName = Request.Cookies["UserName"];
            return View("Index",userName);
        }

        [HttpPost]
        public IActionResult Index(IFormCollection form)
        {
            string userName = form["userName"].ToString();
            CookieOptions option = new CookieOptions();
            option.Expires = DateTime.Now.AddMilliseconds(5);
            Response.Cookies.Append("UserName", userName);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult RemoveCookie()
        {
            Response.Cookies.Delete("UserName");
            return View("Index");
        }
    }
}

aspclass5/Controllers/HiddenController.cs
using aspclass5.Models;
using Microsoft.AspNetCore.Mvc;

namespace aspclass5.Controllers
{
    public class HiddenController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        
        public IActionResult SubmitForm(Hide hide)
        {
            List<Hide> ls = new List<Hide>()
            {
                new Hide()
                {
                    CardHolderName="jeni",
                    Cvv=111
                     
                },
                 new Hide()
                {
                    CardHolderName="bbb",
                    Cvv=222

                },
                  new Hide()
                {
                    CardHolderName="ccc",
                    Cvv=333

                }

            };
            ViewBag.somedata = ls;

            return View();
        }
    }
}

aspclass5/Controllers/HomeController.cs
using aspclass5.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace aspclass5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

aspclass5/Controllers/QueryController.cs
using Microsoft.AspNetCore.Mvc;

namespace aspclass5.Controllers
{
    public class QueryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult QueryTesting()
        {
            string name = "FeraLuxe";
            if (!string.IsNullOrEmpty(HttpContext.Request.Query["name"]))
                name = HttpContext.Request.Query["name"];
            return Content("Welcome " + name);
        }

        public IActionResult DisplayData(string name)
        {
            ViewData["name"] = name ;
            return View();
        }
    }
}

aspclass5/Controllers/SessionController.cs
using Microsoft.AspNetCore.Mvc;

namespace aspclass5.Controllers
{
    public class SessionController : Controller
    {
        const string sName = "_Name";
        const string sCity = "_City";
        public IActionResult Index()
        {
            HttpContext.Session.SetString(sName, "aaa");
            HttpContext.Session.SetString(sCity, "Goa");
            return View();
        }

        public IActionResult Show()
        {
            ViewBag.Name = HttpContext.Session.GetString(sName);
            ViewBag.City = HttpContext.Session.GetString(sCity);
            TempData["sessionid"] = HttpContext.Session.Id;
            ViewData["Message"] = "Session Management in asp.ner core web app";
            return View();
        }
    }
}

aspclass5/Controllers/ShopController.cs
using aspclass5.Models;
using Microsoft.AspNetCore.Mvc;

namespace aspclass5.Controllers
{
    public class ShopController : Controller
    {
        public IActionResult Index()
        {
            ViewData["welcome"] = "Welcome to the property botique shop";
            ViewBag.greetings = "Welcome all..Get 20% on your first service";
            TempData["message"] = "Hello from Temp Data";
            return View();
        }
        public IActionResult Purchase()
        {
            List<Shopping> ls = new List<Shopping>()
            { 
                new Shopping()
            {
                RegNo=1001,
                ShopName="Miramax",
                Location="chennai",
                CustomerRating=5
            },
                 new Shopping()
            {
                RegNo=1002,
                ShopName="Fera",
                Location="ECR",
                CustomerRating=4
            },
                  new Shopping()
            {
                RegNo=1003,
                ShopName="Jgroup",
                Location="Vellore",
                CustomerRating=3
            }
            };
            // ViewBag.ShopDetails = ls;
            ViewData["ShopDetails"] = ls;
            
           
            return View();
        }

        public IActionResult DisplayMessage()
        {
            string message = TempData["message"] as string;
            return View("DisplayMessage", message);
        }
    }
}

aspclass5/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    string[] propLocation = { "chennai", "kerala", "ap" };
    @foreach(var i in propLocation)
    {
        <p>@i</p>
    }
}

<html>
    <body>
        @for(var i=1;i<=10;i++)
    {
        @i
    }
</body>
</html>

aspclass5/Views/Query/DisplayData.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var data = ViewData["name"].ToString();
}
<h2>@data</h2>

aspclass5/Views/Session/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h1>Session data is created</h1>
<div>
    <a asp-controller="Session" asp-action="Show">View Session Data</a>
</div>

aspclass5/Views/Session/Show.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h1>ViewData["Message"]</h1>
<div>
    Name : <h3>@ViewBag.Name</h3>
    City : <h3>@ViewBag.City</h3>
</div>

aspclass5/Views/Shop/DisplayMessage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Display Message</h1>
@if(Model!=null)
{
    <p>@Model</p>
}
else
{
    <p> No message to display</p>
}

aspclass5/Views/Shop/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div>
    <h1>@ViewBag.greetings</h1>
    <p>@ViewData["welcome"]</p>
</div>

aspclass5/Views/Shop/Purchase.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<Shopping>
<div>
    @{
        <p>
        @foreach(var i in (IEnumerable<Shopping>) ViewData["ShopDetails"])
            {
                <table>
                <tr>
                <td>Registration Number</td>
                <td>@i.RegNo</td>
                </tr>
                  <tr>
                <td>Shop Name</td>
                <td>@i.ShopName</td>
                </tr>
                  <tr>
                <td>Location</td>
                <td>@i.Location</td>
                </tr>
                  <tr>
                <td>Customer Rating</td>
                <td>@i.CustomerRating</td>
                </tr>
                </table>
            }

        </p>
    }
</div>